in ~/Documents/Maude_Metacontrol/comfort_controller.maude
in ~/Documents/Maude_Metacontrol/eco_controller.maude
in ~/Documents/Maude_Metacontrol/heater_err_controller.maude
in ~/Documents/Maude_Metacontrol/wh_error_controller.maude
in ~/Documents/Maude_Metacontrol/window_error_controller.maude

mod METACONTROL is
  protecting COMFORTCONTROLLER .
  protecting ECOCONTROLLER .
  protecting HEATERERRCONTROLLER .
  protecting WATERHEATERERRCONTROLLER .
  protecting WINDOWERRCONTROLLER .


endm
