in manager.maude
***in break.maude
in error_msg.maude

mod TEST is
  protecting MANAGER .
  protecting ERRORMSG .
  ***protecting BREAK .

  vars T C AQ : Oid .
  var DG : Temperature .
  var TI : Time .
  var HS : HeaterStatus .
  var WS : WindowStatus .
  var AQS : AirqualityStatus .
  vars CONF : Configuration .
  vars ET ET1 ET2 : EffectTemp .


  op init2 : -> Configuration .
  eq init2 = < "homeHeater" :Heater | Status: hOff, EffectTemp: 0.615, EffectAQ: -0.45, Broken: no >
            < "homeWaterheater" :Waterheater | Status: whOff, EffectTemp: 0.3, EffectAQ: -0.125, Broken: no >
            < "homeWindow" :Window | Status: closed, EffectTemp: -1.0, EffectAQ: 1.0, Broken: no >
            < "homeThermometer" :Thermometer | Degrees: 21.0 >
            < "homeAirquality" :Airquality | Value: 2.0 >
            < "homeClock" :Clock | Timesteps: 0, Time: 0, TempLog: nil, AqLog: nil >
            < "homeComfortController" :ComfortController | Selected: false >
            < "homeEcoController" :EcoController | Selected: true >
            < "homeHeaterErrController" :HeaterErrController | Selected: false >
            < "homeWaterheaterErrController" :WaterheaterErrController | Selected: false >
            < "homeWindowErrController" :WindowErrController | Selected: false >
            < "homeMetacontroller" :Metacontroller >
            < "homeQaComfort" :QaComfort | Consider: 5, Past: nil, Status: 1, QAComputed: no >
            < "homeQaAirquality" :QaAirquality | Consider: 5, Past: nil, Status: 1, QAComputed: no >
            < "homeQaEcology" :QaEcology | Consider: 5, Past: nil, Status: 1, QAComputed: no >
            < Scheduler | Status: MCChange, TempAqChange: false, McChange: false, ContrChange: false > .

  op init3 : -> Configuration .
  eq init3 = < "homeHeater" :Heater | Status: hOff, EffectTemp: 0.615, EffectAQ: -0.45, Broken: no >
            < "homeWaterheater" :Waterheater | Status: whOff, EffectTemp: 0.3, EffectAQ: -0.125, Broken: no >
            < "homeWindow" :Window | Status: closed, EffectTemp: -1.0, EffectAQ: 1.0, Broken: no >
            < "homeThermometer" :Thermometer | Degrees: 15.0 >
            < "homeAirquality" :Airquality | Value: 1.0 >
            < "homeClock" :Clock | Timesteps: 0, Time: 0, TempLog: nil, AqLog: nil > .

  op init4 : -> TimedConfiguration .
  eq init4 = {< "homeHeater" :Heater | Status: hOff, EffectTemp: (scale * 0.615), EffectAQ: (scale * -0.45), Broken: no >
            < "homeWaterheater" :Waterheater | Status: whOff, EffectTemp: (scale * 0.3), EffectAQ: (scale * -0.125), Broken: no >
            < "homeWindow" :Window | Status: closed, EffectTemp: (scale * -1.0), EffectAQ: (scale * 1.0), Broken: no >
            < "homeThermometer" :Thermometer | Degrees: 20.5 >
            < "homeAirquality" :Airquality | Value: 2.0 >
            < "homeClock" :Clock | Timesteps: 0, Time: 0, TempLog: nil, AqLog: nil >
            < "homeComfortController" :ComfortController | Selected: true >
            < "homeEcoController" :EcoController | Selected: false >
            < "homeHeaterErrController" :HeaterErrController | Selected: false >
            < "homeWaterheaterErrController" :WaterheaterErrController | Selected: false >
            < "homeWindowErrController" :WindowErrController | Selected: false >
            ***< "homeMetacontroller" :Metacontroller >
            < "homeQaEcology" :QaEcology | Consider: 10, Past: nil, Status: 1, QAComputed: no >
            < "homeQaComfort" :QaComfort | Consider: 10, Past: nil, Status: 1, QAComputed: no >
            < "homeQaAirquality" :QaAirquality | Consider: 10, Past: nil, Status: 1, QAComputed: no >
            < Scheduler | Status: PhysicsChange, TempAqChange: false, McChange: false, ContrChange: false >} .

  op init5 : -> TimedConfiguration .
  eq init5 = {< "homeHeater" :Heater | Status: hOff, EffectTemp: 0.615, EffectAQ: -0.4, Broken: no >
            < "homeWaterheater" :Waterheater | Status: whOff, EffectTemp: 0.3, EffectAQ: -0.125, Broken: no >
            < "homeWindow" :Window | Status: closed, EffectTemp: -1.0, EffectAQ: 1.0, Broken: no >
            < "homeThermometer" :Thermometer | Degrees: 20.5 >
            < "homeAirquality" :Airquality | Value: 2.0 >
            < "homeClock" :Clock | Timesteps: 0, Time: 0, TempLog: nil, AqLog: nil >
            < "homeComfortController" :ComfortController | Selected: true >
            < "homeEcoController" :EcoController | Selected: false >
            < Scheduler | Status: PhysicsChange, TempAqChange: false, McChange: false, ContrChange: false >} .


endm
eof

search [1, 1000] init5 =>* {CONF:Configuration} such that getTemp(CONF) < 18.0 .

search [1, 1000] init5 =>* {CONF:Configuration} such that getTemp(CONF) > 22.0 .

search [1, 1000] init5 =>* {CONF:Configuration} such that getAirquality(CONF) < 0.0 .

*** With metacontroller
search [1, 5000] init4 =>* {CONF:Configuration} such that getTemp(CONF) < 18.0 .

search [1, 5000] init4 =>* {CONF:Configuration} such that getTemp(CONF) > 22.0 .

search [1, 5000] init4 =>* {CONF:Configuration} such that getAirquality(CONF) < 0.0 .



*** Old searches
search [1] init =>* CONF:Configuration such that getTemp(CONF) <= 0.0 .

search [1] init2 =>* CONF:Configuration such that getTemp(CONF) <= 17.0 /\ getTime(CONF) <= 30 /\ getAirquality(CONF) <= 2.0 .


search [1] init2 =>* CONF:Configuration such that getTemp(CONF) <= 17.0 /\ getTime(CONF) <= 50 .


search [1] init =>* CONF:Configuration such that getTime(CONF) == 10 .

search [1] init2 =>* CONF:Configuration such that getTime(CONF) == 10 .


search [1] init2
           =>*
           < "heterPreferingController" :Controller1 | Selected: true >
           < "windowPreferingController" :Controller2 | Selected: false >
           < "homeHeater" :Heater | Status: HS, RuleAppliedTemp: RA1, RuleAppliedAQ: no, EffectTemp: ET1 >
           < "homeWindow" :Window | Status: WS, RuleAppliedTemp: RA2, RuleAppliedAQ: no, EffectTemp: ET2 >
           < "homeThermometer" :Thermometer | Degrees: DG >
           < "homeClock" :Clock | Time: 10 > .


search [1] init =>* CONF:Configuration such that CONF == init .

search [1] < "homeHeater" :Heater | Status: veryhot, EffectTemp: 0.2 >
          < "homeWindow" :Window | Status: open, EffectTemp: -0.2 >
          < "homeThermometer" :Thermometer | Degrees: 20.0 >
          < "homeClock" :Clock | Time: 0 >
           =>*
           < "homeHeater" :Heater | Status: HS, RuleAppliedTemp: RA1, RuleAppliedAQ: no, EffectTemp: ET1 >
           < "homeWindow" :Window | Status: WS, RuleAppliedTemp: RA2, RuleAppliedAQ: no, EffectTemp: ET2 >
           < "homeThermometer" :Thermometer | Degrees: DG >
           < "homeClock" :Clock | Time: TI >
           such that TI == 0 /\ DG == 20.0 /\ ET1 == 0.2 /\ ET2 == - 0.2
           /\ HS == veryhot /\ WS == open /\ RA1 == no /\ RA2 == no .

search [1] < "homeHeater" :Heater | Status: veryhot, EffectTemp: 0.2 >
           < "homeWindow" :Window | Status: open, EffectTemp: -0.2 >
           < "homeThermometer" :Thermometer | Degrees: 20.0 >
           < "homeClock" :Clock | Time: 0 >
            =>*
            < "homeHeater" :Heater | Status: veryhot, EffectTemp: 0.2 >
            < "homeWindow" :Window | Status: open, EffectTemp: -0.2 >
            < "homeThermometer" :Thermometer | Degrees: 20.0 >
            < "homeClock" :Clock | Time: 0 > .
