mod SCHEDULER is
  protecting ACTUATORS .

  sort Scheduler ScheduleComponents .
  subsort Scheduler < Configuration .

  ops PhysicsChange QAChange MCAnalyse MCPlan ContrChange TimeChange : -> ScheduleComponents .

  *** The scheduler indicates which part of the system should apply rules at the moment
  op < Scheduler | Status: _, RuleApplied: _ > : ScheduleComponents Bool  -> Scheduler [format(ntc c c c c c c c c c)].

endm
